"use client";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { ExploreHeader, JourneySummary } from "@/components/ExploreHeader";
import { filterMerchants } from "@/lib/merchants";
import { merchantImageSrc } from "@/lib/merchant-assets";
import { getDemoReachability } from "@/lib/demo-context";

export default function A4Page() {
  const router = useRouter();
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState<"all" | "partner">("all"); const [selected, setSelected] = useState("samjin");
  useEffect(() => { const params = new URLSearchParams(window.location.search); setQuery(params.get("q") ?? ""); setFilter(params.get("filter") === "partner" ? "partner" : "all"); }, []);
  const reachableIds = useMemo(() => new Set(getDemoReachability().filter((result) => result.reachable).map((result) => result.merchantId)), []);
  const items = useMemo(() => filterMerchants(query, filter).filter((merchant) => reachableIds.has(merchant.id)), [query, filter, reachableIds]); const selectedMerchant = items.find((item) => item.id === selected) ?? items[0];
  const sync = (nextQuery = query, nextFilter = filter) => `?q=${encodeURIComponent(nextQuery)}&filter=${nextFilter}`;
  return <main className="explore-page"><ExploreHeader /><JourneySummary /><div className="view-tabs"><button type="button" className="active">지도</button><button type="button" onClick={() => router.push(`/a5${sync()}`)}>리스트</button></div><input className="search-box" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="매장명, 상품명으로 검색" aria-label="매장 검색" /><div className="filter-chips"><button type="button" className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>전체</button><button type="button" className={filter === "partner" ? "active" : ""} onClick={() => setFilter("partner")}>제휴 매장</button><button type="button">선물</button><button type="button">먹거리</button><button type="button">철도 배송 가능</button></div><div className="mock-map" aria-label="부산역 주변 매장 지도"><div className="map-block block-one"/><div className="map-block block-two"/><div className="map-road major"><span>중앙대로</span></div><div className="map-road cross"><span>충장대로</span></div><div className="map-walk walk-one"/><div className="map-walk walk-two"/><div className="map-landmark station-label">부산역 광장</div><div className="map-station">부산역<br/><small>현재 위치</small></div>{items.map((merchant, index) => <button type="button" key={merchant.id} className={`map-marker m${index + 1} ${selectedMerchant?.id === merchant.id ? "selected" : ""}`} onClick={() => setSelected(merchant.id)} aria-label={`${merchant.name} 선택`}>{merchant.isPartner ? "◆" : "●"}</button>)}</div>{selectedMerchant ? <section className="map-detail"><div className="map-detail-photo"><img src={merchantImageSrc[selectedMerchant.id]} alt="" /></div><div><h2>{selectedMerchant.name}　›</h2><p>⌖ 부산역에서 {selectedMerchant.distance} · 도보 {selectedMerchant.walkingTime}</p><p>{selectedMerchant.representativeProduct}</p><div>{selectedMerchant.isPartner && selectedMerchant.railShippingEnabled && <span className="tag blue">철도 배송 가능</span>}{selectedMerchant.isPartner && <span className="tag green">앱 주문 가능</span>}</div><button type="button" onClick={() => router.push(selectedMerchant.isPartner ? `/a6?id=${selectedMerchant.id}` : `/a7?id=${selectedMerchant.id}`)}>매장 상세　›</button></div></section> : <p className="empty-state">현재 방문·배송 가능한 매장이 없습니다.</p>}<p className="result-count">부산역 주변 이용 가능 매장 {items.length}곳　›</p></main>;
}
