"use client";

import { useRouter } from "next/navigation";
import { PrimaryBottomNav } from "@/components/PrimaryBottomNav";

const quickBenefits = [["🗓️", "정기권"], ["🪪", "N카드"], ["✳️", "특가상품"]];
const services = [["🗺️", "길안내"], ["🅿️", "주차·정산"], ["🚌", "공항버스"], ["☕", "커피&빵"], ["🚗", "렌터카"], ["🚙", "카셰어링"], ["🏨", "숙박"], ["🚠", "레저이용권"], ["🚕", "관광택시"], ["🧳", "짐배송"], ["🚆", "레일택배"], ["🛍️", "쇼핑"]];

export default function HomePage() { const router = useRouter(); return <main className="korail-home"><header className="korail-home-header"><div className="status-row"><span>02:34 ◢</span><span>▮▮▮ LTE　▰</span></div><div className="brand-row"><strong>KORAIL</strong><div><button type="button" className="large-mode">큰글씨모드　›</button><button type="button" aria-label="알림">♧</button><button type="button" aria-label="장바구니">🛒</button></div></div></header><section className="journey-hero"><h1>어디로 떠나볼까요?</h1><section className="booking-card"><div className="station-row"><button type="button"><small>출발역</small><b>오산　›</b></button><span>⇄</span><button type="button"><small>도착역</small><b>서울　›</b></button></div><button type="button" className="date-field"><span>가는날</span><b>2026년 8월 13일 (목) 02:18</b></button><div className="booking-options"><button type="button"><span>인원</span><b>어른 1명</b></button><button type="button"><span>좌석</span><b>일반 좌석</b></button></div><div className="booking-actions"><button type="button">간편 예매</button><button type="button">열차 조회</button></div></section></section><section className="home-content"><div className="rail-banner">코레일-SR 통합 철도회원 전환 안내 <span>🚄　🚆</span></div><section className="benefit-grid">{quickBenefits.map(([icon, label]) => <button type="button" key={label}><span>{icon}</span>{label}</button>)}</section><section className="service-grid">{services.map(([icon, label]) => <button type="button" key={label} onClick={() => label === "쇼핑" && router.push("/shop")}><span>{icon}</span>{label}</button>)}</section><button type="button" className="train-map-card"><span>🚆</span><div><b>열차 지도 보기</b><small>모든 열차 운행 정보를 한 눈에 확인</small></div><i>›</i></button></section><PrimaryBottomNav active="home" /></main>; }
