export type EntrySource = "OFFLINE_QR" | "ONLINE_CART";
export type ShippingEntryPayload = { version: 1; source: EntrySource; orderId: string; merchantId: string; orderItems: { productId: string; productName: string; quantity: number; unitPrice?: number; selectedOption?: string; packagingOption?: string }[]; packages?: { merchantPackageTypeId: string; quantity: number }[]; productCategory?: string; iceBoxPackaging?: boolean };
export type RailwayPackageAssignment = { className: "MINI" | "STANDARD" | "LARGE"; quantity: number; volumeCm3: number; weightKg: number };
export type ShippingOption = { id: string; serviceType: string; available: boolean; price: number; departureAt: string; arrivalAt: string; etaText: string; destinationType: string; recommendationBadge?: string; unavailableReason?: string };
export type ShippingSession = { sessionId: string; source: EntrySource; orderId: string; merchantId: string; merchantName: string; orderItems: ShippingEntryPayload["orderItems"]; merchantPackages: NonNullable<ShippingEntryPayload["packages"]>; railwayPackages: RailwayPackageAssignment[]; recipient?: { name: string; phone: string }; deliveryMode?: "HOME" | "PICKUP"; destination?: { address: string; detail?: string; station?: string }; shippingOptions: ShippingOption[]; selectedShippingOption?: ShippingOption; paymentMethod?: string; paymentStatus?: "PAID_MOCK"; receiptNumber?: string; receiptAt?: string; shipment?: Shipment; trackingStatus: TrackingStatus };
export type TrackingStatus = "BEFORE_DEPARTURE" | "IN_TRANSIT" | "ARRIVED" | "RECEIVED";
export type Shipment = { id: string; trainNo: string; trainDate: string; origin: string; destination: string; departureAt: string; arrivalAt: string; stops: { stationName: string; arrivalAt: string; departureAt: string }[]; currentStopIndex: number };
export const shippingDemoContext = { receiptAt: "2026.08.13 14:20", trainDate: "2026.08.14", origin: "부산역", destination: "서울역", departure: "09:00", arrival: "11:42" };
const merchantPackages = { STORE_BOX_S: [20,15,10,2], STORE_BOX_M: [30,22,18,5], STORE_BOX_L: [40,30,25,10] } as const;
const railway = [{className:"MINI" as const,d:[28,20,15],max:4},{className:"STANDARD" as const,d:[45,35,30],max:15},{className:"LARGE" as const,d:[65,45,40],max:25}];
export const productPackagingProfiles: Record<string, [number,number,number,number,boolean]> = { P001:[24,18,12,1.2,false], default:[28,20,14,1.5,false] };
export function createDemoShippingEntry(): ShippingEntryPayload { return { version:1, source:"OFFLINE_QR", orderId:"20260813-0004821", merchantId:"M001", orderItems:[{productId:"P001",productName:"부산 어묵 종합 선물세트",quantity:2,unitPrice:20000}],packages:[{merchantPackageTypeId:"STORE_BOX_M",quantity:1}],productCategory:"식품",iceBoxPackaging:false }; }
export function decodeShippingEntryPayload(encoded: string): ShippingEntryPayload | null { try { const json = decodeURIComponent(escape(atob(encoded.replace(/-/g,"+").replace(/_/g,"/") + "=".repeat((4-encoded.length%4)%4)))); const p=JSON.parse(json) as ShippingEntryPayload; return p.version===1 && !!p.orderId && Array.isArray(p.orderItems) ? p : null; } catch { try { const p=JSON.parse(encoded) as ShippingEntryPayload; return p.version===1 && !!p.orderId ? p:null; } catch{return null;} } }
export function calculateRailwayPackages(payload: ShippingEntryPayload): RailwayPackageAssignment[] { const units: [number,number,number,number][]=[]; (payload.packages||[]).forEach(p=>{const d=merchantPackages[p.merchantPackageTypeId as keyof typeof merchantPackages]; if(d) for(let i=0;i<p.quantity;i++) units.push([...d]);}); if(!units.length) payload.orderItems.forEach(i=>{const d=productPackagingProfiles[i.productId]||productPackagingProfiles.default; for(let n=0;n<i.quantity;n++) units.push([d[0],d[1],d[2],d[3]]);}); const result:RailwayPackageAssignment[]=[]; for(const unit of units){ const fits=railway.filter(r=>[...unit.slice(0,3)].sort((a,b)=>a-b).every((v,i)=>v<=[...r.d].sort((a,b)=>a-b)[i])); const choice=fits.sort((a,b)=>a.max-b.max)[0]||railway[2]; const found=result.find(r=>r.className===choice.className); const volume=unit[0]*unit[1]*unit[2]; if(found){found.quantity++;found.volumeCm3+=volume;found.weightKg+=unit[3];}else result.push({className:choice.className,quantity:1,volumeCm3:volume,weightKg:unit[3]}); } return result; }
export function generateShippingOptions(s: ShippingSession): ShippingOption[] { const weight=s.railwayPackages.reduce((n,p)=>n+p.weightKg*p.quantity,0); const base=Math.round(weight)*500; const home=s.deliveryMode==="HOME"; const defs=[ ["KTX_EXPRESS","KTX특송",12000,0,"역에서 픽업"],["RAIL_PARCEL","레일택배",7000,5,"집까지 배송"],["AGENT","어전트서비스",4000,30,"집까지 배송"],["KTX_QUICK","KTX특송 + 퀵서비스",15000,2,"집까지 배송"] ] as const; const options: ShippingOption[]=defs.map(([id,type,price,hours,destinationType])=>({id,serviceType:type,available:!(id==="KTX_EXPRESS"&&home),price:price+base,departureAt:"2026.08.14 09:00",arrivalAt:`2026.08.14 ${String(12+hours).padStart(2,"0")}:00`,etaText:hours===0?"내일 11:42 도착":hours<10?`내일 ${14+hours}:00 ~ ${16+hours}:00`:`모레 18:00 ~ 22:00`,destinationType,unavailableReason:id==="KTX_EXPRESS"&&home?"역 픽업 수령 시 이용 가능":undefined})); const available=options.filter(o=>o.available); const minCost=Math.min(...available.map(o=>o.price)), maxCost=Math.max(...available.map(o=>o.price)); available.forEach((o,i)=>{const score=(o.price-minCost)/Math.max(1,maxCost-minCost)+i/Math.max(1,available.length-1); o.recommendationBadge=i===0?"최단시간":o.price===minCost?"최소비용":score===Math.min(...available.map((x,j)=>(x.price-minCost)/Math.max(1,maxCost-minCost)+j/Math.max(1,available.length-1)))?"최적":undefined;}); return options; }
export function normalizeShippingEntry(p: ShippingEntryPayload): ShippingSession { const session: ShippingSession={sessionId:`ship-${p.orderId}`,source:p.source,orderId:p.orderId,merchantId:p.merchantId,merchantName:"부산어묵 부산역점",orderItems:p.orderItems,merchantPackages:p.packages||[],railwayPackages:calculateRailwayPackages(p),shippingOptions:[],trackingStatus:"IN_TRANSIT"}; return session; }
const key="korail-plus-shipping-session"; export function loadShippingSession(){if(typeof window==="undefined")return null;try{return JSON.parse(localStorage.getItem(key)||"null") as ShippingSession|null}catch{return null}} export function saveShippingSession(s:ShippingSession){localStorage.setItem(key,JSON.stringify(s));}
export function createReceiptNumber(){return `20260813-${String(Math.floor(100000+Math.random()*899999))}`;} export function createShipment():Shipment{return {id:"SHP-20260814-005",trainNo:"KTX 005",trainDate:shippingDemoContext.trainDate,origin:shippingDemoContext.origin,destination:shippingDemoContext.destination,departureAt:shippingDemoContext.departure,arrivalAt:shippingDemoContext.arrival,currentStopIndex:2,stops:[{stationName:"부산",arrivalAt:"",departureAt:"09:00"},{stationName:"동대구",arrivalAt:"09:48",departureAt:"09:50"},{stationName:"대전",arrivalAt:"10:45",departureAt:"10:47"},{stationName:"서울",arrivalAt:"11:42",departureAt:""}]};}
export const formatWon=(n:number)=>`${n.toLocaleString("ko-KR")}원`;
