"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getMerchant } from "@/lib/merchants";
import { merchantImageSrc, productImageSrc } from "@/lib/merchant-assets";

const products = [["어묵 선물 세트 1호", "20,000원", "#d69b58"], ["프리미엄 어묵 세트", "29,000원", "#7fa0c2"], ["삼진 어묵 세트", "15,000원", "#bd775d"]] as const;

export default function A6Page() { const router = useRouter(); const [id, setId] = useState("samjin"); useEffect(() => { setId(new URLSearchParams(window.location.search).get("id") ?? "samjin"); }, []); const merchant = getMerchant(id); return <main className="detail-store-page"><header className="store-header"><button type="button" onClick={() => router.back()}>‹</button><h1>매장 상세</h1><span>♡　↗</span></header><div className="store-hero store-photo"><img src={merchantImageSrc[merchant.id]} alt="" /><span>{merchant.category}</span></div><section className="store-intro"><span className="partner-badge">제휴 매장</span><h2>{merchant.name}</h2><p>{merchant.description}</p><p>⌖ 부산역 도보 {merchant.walkingTime}　·　운영시간 {merchant.hours}</p><div><span className="tag blue">철도 배송 가능</span><span className="tag green">앱 주문 가능</span></div></section><section className="store-section"><h3>대표 상품</h3><div className="product-grid">{products.map(([name, price, hue]) => <Product key={name} name={name} price={price} hue={hue} />)}</div></section><section className="guide-section"><h3>이렇게 이용해 보세요</h3><p><b>매장에서 직접 구매</b><br/>상품을 구매한 뒤 철도배송을 이용할 수 있어요.</p><p><b>앱에서 바로 주문</b><br/>제휴 매장은 코레일 앱에서 상품을 주문할 수 있어요.</p></section><section className="shipping-guide"><h3>철도 배송 안내</h3><b>철도 배송 가능</b><p>배송 방법과 예상 운임은 주문 과정에서 확인할 수 있습니다.</p></section><div className="store-cta-row"><button type="button" className="store-directions" onClick={() => alert("실제 서비스에서는 기존 KORAIL+ 길찾기 기능과 연결됩니다.")}>매장 가기</button><button type="button" className="primary-store-cta" onClick={() => router.push(`/shop?merchant=${merchant.id}`)}>앱에서 주문하기</button></div></main>; }
function Product({ name, price, hue }: { name: string; price: string; hue: string }) { return <article className="product-card"><img className="product-art" src={productImageSrc(name, hue)} alt=""/><strong>{name}</strong><span>{price}</span></article>; }
