"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getMerchant } from "@/lib/merchants";
import { merchantImageSrc, productImageSrc } from "@/lib/merchant-assets";

const products = [["부산 감성 엽서 세트", "8,000원", "#7b9ac5"], ["부산 캐릭터 키링", "12,000원", "#d8887d"], ["부산 로컬 선물 세트", "25,000원", "#c6a75c"]] as const;
export default function A7Page() { const router = useRouter(); const [id, setId] = useState("giftshop"); useEffect(() => { setId(new URLSearchParams(window.location.search).get("id") ?? "giftshop"); }, []); const merchant = getMerchant(id); return <main className="detail-store-page"><header className="store-header"><button type="button" onClick={() => router.back()}>‹</button><h1>매장 상세</h1><span>♡　↗</span></header><div className="store-hero store-photo"><img src={merchantImageSrc[merchant.id]} alt="" /><span>{merchant.category}</span></div><section className="store-intro"><span className="registered-badge">일반 등록매장</span><h2>{merchant.name}</h2><p>{merchant.description}</p><p>⌖ 부산역 도보 {merchant.walkingTime}　·　운영시간 {merchant.hours}</p></section><section className="store-section"><h3>대표 상품</h3><div className="product-grid">{products.map(([name, price, hue]) => <Product key={name} name={name} price={price} hue={hue} />)}</div></section><section className="shipping-guide rail-guide"><h3>구매한 상품, 직접 철도배송으로 보내세요</h3><p className="guide-lead">이 매장은 코레일 제휴매장이 아니므로 매장에서 바로 배송을 접수하지 않습니다. 상품 구매 후 고객님이 직접 이용 가능한 철도물류 서비스를 선택해 접수할 수 있습니다.</p><div className="service-guide"><h4>KTX특송</h4><b>빠르게 보내고 싶을 때</b><ol><li>현재 이용 가능한 KTX특송 영업소·서비스를 확인합니다.</li><li>출발역의 KTX특송 접수처에 물품을 접수합니다.</li><li>KTX로 출발역에서 도착역까지 운송됩니다.</li><li>도착역에서 수령합니다.</li></ol><small>실제 이용 가능 노선·운영시간·요금은 KTX특송 운영 안내에서 확인해주세요.</small></div><div className="service-guide"><h4>레일택배</h4><b>집까지 일반택배로 보내고 싶을 때</b><ol><li>코레일유통 또는 연계 택배 접수 화면에서 접수합니다.</li><li>이용 가능한 역·무인 택배 발송지를 확인합니다.</li><li>규격에 맞는 상품을 발송 접수합니다.</li><li>일반 택배 방식으로 목적지까지 배송됩니다.</li></ol><small>서비스 이용 가능 지역과 물품 규격은 실제 접수 단계에서 확인합니다.</small></div></section><button type="button" className="primary-store-cta secondary" onClick={() => alert("실제 서비스에서는 기존 KORAIL+ 길찾기 기능과 연결됩니다.")}>매장 가기</button></main>; }
function Product({ name, price, hue }: { name: string; price: string; hue: string }) { return <article className="product-card"><img className="product-art" src={productImageSrc(name, hue)} alt=""/><strong>{name}</strong><span>{price}</span></article>; }
